### ISSUE TITLE
MultipleSelect should not depend on com.vaading:vaadin but com.vaadin:vaadin-core

### ISSUE THREAD

**Issue by probert94** [vaadin-component-factory/multiple-select#5]
This component depends on the artifact [`vaadin`](https://github.com/vaadin-component-factory/multiple-select/blob/master/pom.xml#L91), which includes `vaadin-core`, but also the pro components like `vaadin-grid-pro-flow` and `vaadin-charts-pro`.
In our case this results in much bigger bundle sizes for the frontend and also gives us access to the pro components (which we are not yet using) in our java code.
I think this component should only depend on `vaadin-core`, as it does not depend on any of the pro components.

I am using version 2.2.0 with Vaadin 17.0.10

**Comment by tarekoraby** [comment]
Fixed in version 2.2.1 of the addon
